CREATE TABLE app_config (
  config_key CHARACTER VARYING(128) PRIMARY KEY,
  config_type CHARACTER VARYING(32) NOT NULL,
  config_value CHARACTER VARYING(1024) DEFAULT NULL,
  config_large_value TEXT DEFAULT NULL
);
